[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-10_x"]

[phases.install]
cmds = ["cd whistlechain && npm ci"]

[phases.build]
cmds = ["cd whistlechain && npm run build"]

[start]
cmd = "cd whistlechain && npm start"

[variables]
NODE_ENV = "production"

